id: "base"
env:
  result_dir: 'results'
  random_seed: 0
  epochs: 10
  solver: 'sklearn-solver'
metrics:
  goal_metric: 'F1'
  save_metrics:
    Accuracy: {num_classes: 4, average: 'macro'}
    Precision: {num_classes: 4, average: 'macro'}
    Recall: {num_classes: 4, average: 'macro'}
    F1: {num_classes: 4, average: 'macro'}
data:
  name: "jigsaw_dataset"
  params:
    dataset_path: '/home/albert/data/jigsaw'
    test_filename: 'comments_to_score.csv'
    batch_size: 16

    category_weights:
      'obscene': 0.16
      'toxic': 0.32
      'threat': 1.5
      'insult': 0.64
      'severe_toxic': 1.5
      'identity_hate': 1.5

    gpu_to_use: 0
    workers: 8
    load_into_memory: false
tokenizer:
  name: "WordPiece"
  params:
    unk_token: "[UNK]"
  normalizer:
    name: "BertNormalizer"
    params:
      lowercase: True
  pre_tokenizer:
    name: "BertPreTokenizer"
    params: {}
  trainer:
    name: "WordPieceTrainer"
    params:
      vocab_size: 25000
      special_tokens: ["[UNK]", "[PAD]", "[CLS]", "[SEP]", "[MASK]"]

model:
  name: "Ridge"
  params:
    alpha: 0.8