id: "singlelabel"
env:
  result_dir: 'results'
  positive_threshold: 0.3
  random_seed: 0
  epochs: 20
metrics:
  goal_metric: 'F1'
  save_metrics:
    Accuracy: {num_classes: 4, average: 'macro'}
    Precision: {num_classes: 4, average: 'macro'}
    Recall: {num_classes: 4, average: 'macro'}
    F1: {num_classes: 4, average: 'macro'}
visualizer:
  vizualized_images: ['GuidedBackprop', 'ScoreCam', 'OcclusionSensitivity']
data:
  name: "cat_dataset"
  params:
    dataset_path: 'dataset'

    batch_size: 16
    input_size: [512, 512]
    input_channels: 3
    num_classes: 4
    balanced_classes: True
    include_negatives: False

    # transforms must be a list to make sure to preserve the order
    transforms: [['ColorJitter', [0.5, 0.5, 0.5, 0.3]],
                 ['RandomRotation', [10]],
                 ['RandomPerspective', [0.4]],
                 ['RandomResizedCrop', [[512, 512], [0.7, 1.3]]],
                 ['RandomChoiceRotation', [[0, 90, 180, 270]]],
                 ['ToTensor', []],
                 ['Normalize', [[0.4432, 0.3938, 0.3764], [0.1560, 0.1815, 0.1727]]]]

    multilabel_classification: False
    single_object_classes: False
    gpu_to_use: 0
    workers: 8
    load_into_memory: false
    train_val_split: [0.8, 0.2]
model:
  name: "resnet18"
  params:
    num_classes: 4
    pretrained: true
loss:
  name: 'FocalLoss'
  params:
    weight: null
optimizer:
  name: 'RAdam'
  params:
    lr: 0.00001
    weight_decay: 0.0001
lr_policy:
  name: 'ReduceLROnPlateau'
  params:
    mode: 'max'
    patience: 3