id: "transformer"
env:
  result_dir: 'results'
  random_seed: 0
  epochs: 10
  solver: 'transformer-solver'

data:
  name: "jigsaw_dataset"
  params:
    dataset_path: '/home/albert/data/jigsaw'
    batch_size: 16
    balanced_classes: True

    category_weights:
      'obscene': 0.16
      'toxic': 0.32
      'threat': 1.5
      'insult': 0.64
      'severe_toxic': 1.5
      'identity_hate': 1.5

    gpu_to_use: 0
    workers: 0
    load_into_memory: false

    clean_text: false

    tokenizer:
      name: 'bert-base-uncased'
      pretrained: True
      tokenize_params:
        truncation: True
        add_special_tokens: True
        max_length: 128
        padding: 'max_length'

    vectorizer: null

model:
  name: 'bert-base-uncased'
  pretrained: True

loss:
  name: 'MSELoss'
  params: {}

optimizer:
  name: 'RAdam'
  params:
    lr: 0.0001
    weight_decay: 0.0001

lr_policy:
  name: 'ReduceLROnPlateau'
  params:
    mode: 'max'
    patience: 3